"""update

Revision ID: 126156b2d21b
Revises: d143952fc194
Create Date: 2024-06-13 22:43:12.490490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126156b2d21b'
down_revision: Union[str, None] = 'd143952fc194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('bot_answers', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('user_messages', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('data', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'message')
    op.drop_column('messages', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('messages', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'date')
    op.drop_column('messages', 'data')
    op.drop_column('messages', 'user_messages')
    op.drop_column('messages', 'bot_answers')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###
