"""update

Revision ID: 78d5f1d632d3
Revises: 126156b2d21b
Create Date: 2024-06-13 23:08:57.614984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78d5f1d632d3'
down_revision: Union[str, None] = '126156b2d21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'bot_answers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'user_messages',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'user_messages',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'bot_answers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
