"""new

Revision ID: d7f200534d18
Revises: 78d5f1d632d3
Create Date: 2024-06-14 07:58:16.512244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f200534d18'
down_revision: Union[str, None] = '78d5f1d632d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'bot_answers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'user_messages',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'user_messages',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'bot_answers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
